### ISSUE TITLE
Exception in 3.0.0

### ISSUE THREAD

**Issue by arranf** [renefloor/flutter_cached_network_image#17]
```
I/flutter (17907): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17907): The following _CompileTimeError was thrown building RawGestureDetector(state:
I/flutter (17907): RawGestureDetectorState#75609(gestures: [tap])):
I/flutter (17907): 'package:cached_network_image/cached_network_image.dart': error: line 252 pos 15: unexpected token
I/flutter (17907): 'void'
I/flutter (17907):         .then<void>((CachedNetworkImageProvider key) {
I/flutter (17907):               ^
I/flutter (17907): 
I/flutter (17907): When the exception was thrown, this was the stack:
I/flutter (17907): #0      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3660:12)
I/flutter (17907): #1      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
I/flutter (17907): #2      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
I/flutter (17907): #3      Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
I/flutter (17907): #4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4532:14)
I/flutter (17907): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
I/flutter (17907): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
I/flutter (17907): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4532:14)
I/flutter (17907): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
I/flutter (17907): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
I/flutter (17907): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #12     StatefulElement.update (package:flutter/src/widgets/framework.dart:3681:5)
I/flutter (17907): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:3606:5)
I/flutter (17907): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter (17907): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #22     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4261:32)
I/flutter (17907): #23     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4647:17)
I/flutter (17907): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #25     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4261:32)
I/flutter (17907): #26     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4647:17)
I/flutter (17907): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #32     StatelessElement.update (package:flutter/src/widgets/framework.dart:3606:5)
I/flutter (17907): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #36     ProxyElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter (17907): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #40     StatefulElement.update (package:flutter/src/widgets/framework.dart:3681:5)
I/flutter (17907): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #46     StatelessElement.update (package:flutter/src/widgets/framework.dart:3606:5)
I/flutter (17907): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #52     StatefulElement.update (package:flutter/src/widgets/framework.dart:3681:5)
I/flutter (17907): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #56     StatefulElement.update (package:flutter/src/widgets/framework.dart:3681:5)
I/flutter (17907): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #62     StatelessElement.update (package:flutter/src/widgets/framework.dart:3606:5)
I/flutter (17907): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #68     StatelessElement.update (package:flutter/src/widgets/framework.dart:3606:5)
I/flutter (17907): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #70     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #74     StatelessElement.update (package:flutter/src/widgets/framework.dart:3606:5)
I/flutter (17907): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #78     StatelessElement.update (package:flutter/src/widgets/framework.dart:3606:5)
I/flutter (17907): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #84     StatelessElement.update (package:flutter/src/widgets/framework.dart:3606:5)
I/flutter (17907): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #88     ProxyElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter (17907): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #92     StatefulElement.update (package:flutter/src/widgets/framework.dart:3681:5)
I/flutter (17907): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #94     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:696:34)
I/flutter (17907): #95     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:665:7)
I/flutter (17907): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #99     ProxyElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter (17907): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #101    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #103    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4261:32)
I/flutter (17907): #104    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4647:17)
I/flutter (17907): #105    _ViewportElement.update (package:flutter/src/widgets/viewport.dart:182:17)
I/flutter (17907): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #109    ProxyElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter (17907): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #111    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #119    StatefulElement.update (package:flutter/src/widgets/framework.dart:3681:5)
I/flutter (17907): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4539:14)
I/flutter (17907): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #128    Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #129    StatelessElement.update (package:flutter/src/widgets/framework.dart:3606:5)
I/flutter (17907): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #132    Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #133    StatefulElement.update (package:flutter/src/widgets/framework.dart:3681:5)
I/flutter (17907): #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #136    Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #137    StatefulElement.update (package:flutter/src/widgets/framework.dart:3681:5)
I/flutter (17907): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #140    Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #141    ProxyElement.update (package:flutter/src/widgets/framework.dart:3791:5)
I/flutter (17907): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2649:15)
I/flutter (17907): #143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
I/flutter (17907): #144    Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
I/flutter (17907): #145    StatelessElement.update (package:flutter/src/widgets/framework.dart:3606:5)
```

**Comment by renefloor** [comment]
RawGestureDetector(state:: RawGestureDetectorState#75609(gestures: [tap])). Not sure what happens here. Can you show me your code and the flutter version you are using?

**Comment by renefloor** [comment]
Closed this issue for now until we have more information
