### ISSUE TITLE
 android.database.sqlite.SQLiteDatabaseLockedException: database is locked

### ISSUE THREAD

**Issue by duanyuGit** [renefloor/flutter_cached_network_image#184]
Failed to open database '/data/user/0/com.gcenter.game_center/databases/libCachedImageData.db'.
E/SQLiteDatabase(18938): android.database.sqlite.SQLiteDatabaseLockedException: database is locked (Sqlite code 5): , while compiling: PRAGMA journal_mode, (OS error - 11:Try again)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:925)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:670)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:356)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:330)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:229)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:511)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:194)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:864)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:767)
E/SQLiteDatabase(18938): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:742)
E/SQLiteDatabase(18938): 	at com.tekartik.sqflite.SqflitePlugin$Database.open(SqflitePlugin.java:828)
E/SQLiteDatabase(18938): 	at com.tekartik.sqflite.SqflitePlugin$Database.access$800(SqflitePlugin.java:815)
E/SQLiteDatabase(18938): 	at com.tekartik.sqflite.SqflitePlugin.onOpenDatabaseCall(SqflitePlugin.java:666)
E/SQLiteDatabase(18938): 	at com.tekartik.sqflite.SqflitePlugin.onMethodCall(SqflitePlugin.java:771)
E/SQLiteDatabase(18938): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/SQLiteDatabase(18938): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/SQLiteDatabase(18938): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/SQLiteDatabase(18938): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/SQLiteDatabase(18938): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/SQLiteDatabase(18938): 	at android.os.Looper.loop(Looper.java:144)
E/SQLiteDatabase(18938): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/SQLiteDatabase(18938): 	at java.lang.reflect.Method.invoke(Native Method)
E/SQLiteDatabase(18938): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/SQLiteDatabase(18938): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/flutter (18938): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DatabaseException(database is locked (Sqlite code 5): , while compiling: PRAGMA journal_mode, (OS error - 11:Try again))
E/flutter (18938): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29:7)
E/flutter (18938): #2      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:183:15)
E/flutter (18938): #3      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.openDatabase (package:sqflite/src/database_mixin.dart:503:15)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #4      _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.doOpen (package:sqflite/src/database_mixin.dart:594:28)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #5      SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:32:22)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #6      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite/src/factory_mixin.dart:100:43)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #7      ReentrantLock.synchronized.<anonymous closure>.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:33:24)
E/flutter (18938): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (18938): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (18938): #10     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (18938): #11     runZoned (dart:async/zone.dart:1463:12)
E/flutter (18938): #12     ReentrantLock.synchronized.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:32:24)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #13     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #14     ReentrantLock.synchronized (package:synchronized/src/reentrant_lock.dart:28:17)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #15     _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.openDatabase (package:sqflite/src/factory_mixin.dart:66:17)
E/flutter (18938): #16     openDatabase (package:sqflite/sqflite.dart:146:26)
E/flutter (18938): #17     CacheObjectProvider.open (package:flutter_cache_manager/src/cache_object.dart:75:16)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #18     CacheStore._openDatabaseConnection.<anonymous closure> (package:flutter_cache_manager/src/cache_store.dart:102:26)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #19     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #20     CacheStore._openDatabaseConnection (package:flutter_cache_manager/src/cache_store.dart:100:36)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #21     CacheStore._getCacheDataFromDatabase (package:flutter_cache_manager/src/cache_store.dart:80:26)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #22     CacheStore.retrieveCacheData (package:flutter_cache_manager/src/cache_store.dart:60:7)
E/flutter (18938): #23     CacheStore.getFile (package:flutter_cache_manager/src/cache_store.dart:43:29)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #24     BaseCacheManager.getFileFromCache (package:flutter_cache_manager/src/cache_manager.dart:135:24)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #25     BaseCacheManager.getFile (package:flutter_cache_manager/src/cache_manager.dart:108:27)
E/flutter (18938): <asynchronous suspension>
E/flutter (18938): #26     CachedNetworkImageState._animatedWidget (package:cached_network_image/src/cached_image_widget.dart:261:12)
E/flutter (18938): #27     CachedNetworkImageState.build (package:cached_network_image/src/cached_image_widget.dart:194:12)
E/flutter (18938): #28     StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
E/flutter (18938): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
E/flutter (18938): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (18938): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (18938): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter (18938): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (18938): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (18938): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (18938): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (18938): #37

**Comment by 229106948** [comment]
I have the same problem,Have you solved it?

**Comment by renefloor** [comment]
I'd guess this is fixed in 1.0.0, if not please reopen this issue.

**Comment by MrVipinVijayan** [comment]
3.2.1 causes the below issue
Warning database has been locked for 0:00:10.000000. Make sure you always use the transaction object for database operations during a transaction and then the app losts connection to device.
