### ISSUE TITLE
FileSystemException (OS Error: Is a directory, errno = 21)

### ISSUE THREAD

**Issue by RobinManoli** [renefloor/flutter_cached_network_image#252]
I was starting my app in flight mode (no internet connection) to check if cached network images would reload automatically when I turned internet access back on. The urls are stored in firestore, so not sure if the urls were cached or not.

(Firestore does automatically update data when internet is turned back on, but cached network images are only displayed when their widgets are reloaded)

When turning internet back on this exception happened:
```
I/flutter (10496): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (10496): The following FileSystemException was thrown resolving an image codec:
I/flutter (10496): Cannot open file, path = '/data/user/0/se.myapp/cache/libCachedImageData' (OS Error: Is
I/flutter (10496): a directory, errno = 21)
I/flutter (10496): 
I/flutter (10496): When the exception was thrown, this was the stack:
I/flutter (10496): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
I/flutter (10496): (elided 13 frames from package dart:async)
I/flutter (10496): ...
I/flutter (10496): 
I/flutter (10496): Path: /data/user/0/se.myapp/cache/libCachedImageData
I/flutter (10496): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by bartektartanus** [comment]
I'm also having this issue. This is the most common error in my Firebase Crashlytics service.

**Comment by renefloor** [comment]
Do you have any idea why or when this happens? The path in the exception is the folder where the files should be put in.

**Comment by RobinManoli** [comment]
If I remember correctly the issue might happen after upgrading
cached_network_image from an old version

Den tis 5 nov. 2019 07:47Rene Floor <notifications@github.com> skrev:

**Comment by nihalreddy33** [comment]
Even I am facing this issue a lot with the new plugin update.

**Comment by aaalekseev** [comment]
Same thing on version 2.0.0

**Comment by vtisnado** [comment]
Same error with:
`cached_network_image: ^2.0.0`

**Comment by renefloor** [comment]
If you have a reproducable example that would be great, because I'm not sure where this is going wrong.

**Comment by devonik** [comment]
I also get the expeption. But when I restart the app it's working. The issue only appears sometimes.

When it's happen I get:

`Cannot open file, path = '/data/user/0/devnik.dev_releases/cache/libCachedImageData/7098d680-6ba2-11ea-df5e-1fe59d7e16db.octet-stream' (OS Error: No such file or directory, errno = 2)`

Why it tries to open a .octet-stream file? Its a normal image. 

Someone knows a workaround to refresh the cached images if it fails ?

I also use `cached_network_image: ^2.0.0`

**Comment by Saifallak** [comment]
i get the same behavior as @devonik , any updates on this ?

**Comment by devonik** [comment]
> 
> 
> i get the same behavior as @devonik , any updates on this ?

No solution right now. I will try to use another library [cache_image](https://pub.dev/packages/cache_image). It comes with firebase support and reloading if failed

**Comment by pavannx** [comment]
Same issue here, but I trying to download a PDF file..

**Comment by Elghandour-eng** [comment]
> I also get the expeption. But when I restart the app it's working. The issue only appears sometimes.
> 
> When it's happen I get:
> 
> ```
> ════════ Exception caught by image resource service ════════════════════════════════════════════════
> The following FileSystemException was thrown resolving an image codec:
> Cannot open file, path = '/data/user/0/devnik.dev_releases/cache/libCachedImageData/31e512d0-6c49-11ea-dc7d-c3a13eec1fc5.octet-stream' (OS Error: No such file or directory, errno = 2)
> 
> When the exception was thrown, this was the stack: 
> #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
> (elided 13 frames from package dart:async)
> Path: /data/user/0/devnik.dev_releases/cache/libCachedImageData/31e512d0-6c49-11ea-dc7d-c3a13eec1fc5.octet-stream
> ════════════════════════════════════════════════════════════════════════════════════════════════════
> ```
> 
> Why it tries to open a .octet-stream file? Its a normal image.
> 
> Someone knows a workaround to refresh the cached images if it fails ?
> 
> I also use `cached_network_image: ^2.0.0`
> 
> If I restart the app and the app is able to read the cached file I get (it can read the .png file instead of .octet-stream):
> 
> ![grafik](https://user-images.githubusercontent.com/16446467/77252057-3e814a00-6c52-11ea-961b-38f2e3e95eed.png)
> Debugged in `flutter\flutter\packages\flutter\lib\src\painting\image_provider.dart (line: 649)`

i have same issue 
did you Solve it?
