### ISSUE TITLE
Update UUID version

### ISSUE THREAD

**Issue by SeniorIvan** [renefloor/flutter_cached_network_image#62]
I have same issue
https://github.com/flutter/flutter/issues/20039

```
Error: Getter not found: 'PI'.
compiler message:   static final TAU = 2*PI;
```

**Comment by vu111293** [comment]
I have same issue. Please upgrade uuid lib. Tks

**Comment by acudworth** [comment]
likewise

**Comment by alegsm** [comment]
Same issue. This leaves this lib incompatible with flutter's latest version

**Comment by codeZee** [comment]
Ditto, looking forward to this fix/update!

**Comment by Shu-Ji** [comment]
@Cretezy 
_cacheData is null sometimes:

![image](https://user-images.githubusercontent.com/1127594/44839027-4b091080-ac70-11e8-9a5a-1b43784ab780.png)

```
I/flutter ( 9513): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 9513): The following NoSuchMethodError was thrown resolving an image codec:
I/flutter ( 9513): The method 'containsKey' was called on null.
I/flutter ( 9513): Receiver: null
I/flutter ( 9513): Tried calling: containsKey("http://xx.com/demo.jpg")
I/flutter ( 9513): 
I/flutter ( 9513): When the exception was thrown, this was the stack:
I/flutter ( 9513): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:47:5)
I/flutter ( 9513): #1      CacheManager.getFile (package:flutter_cache_manager/flutter_cache_manager.dart:191:21)
I/flutter ( 9513): <asynchronous suspension>
I/flutter ( 9513): #2      CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart:469:35)
I/flutter ( 9513): <asynchronous suspension>
I/flutter ( 9513): #3      CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:459:16)
```
